### ISSUE TITLE
module not found createmidieventforbass

### ISSUE THREAD

**Issue by Shriyash-Jagtap** [cognitive-catalyst/watson-beat#21]
after running  wbDev.py it shows

Traceback (most recent call last):
  File "wbDev.py", line 2, in <module>
    from Skeleton import Skeleton
  File "F:\watson-beat-master\src\Skeleton\Skeleton.py", line 3, in <module>
    from Arranging.ArrangeSections import *
  File "F:\watson-beat-master\src\Arranging\ArrangeSections.py", line 5, in <module>
    import CreateMidiEventsForBass
ModuleNotFoundError: No module named 'CreateMidiEventsForBass'

**Comment by shenrichs** [comment]
I get the same eror on Mac OSX Mojaver 10.14.6
