### ISSUE TITLE
Runitime error re: CreateMidiEventsForBass

### ISSUE THREAD

**Issue by shenrichs** [cognitive-catalyst/watson-beat#23]
On Mac OSX Mojave 10.14.6 I get this runtime error:

Traceback (most recent call last):
  File "wbDev.py", line 2, in <module>
    from Skeleton import Skeleton
  File "/Users/stevehenrichs/watson-beat/src/Skeleton/Skeleton.py", line 3, in <module>
    from Arranging.ArrangeSections import *
  File "/Users/stevehenrichs/watson-beat/src/Arranging/ArrangeSections.py", line 5, in <module>
    import CreateMidiEventsForBass
ModuleNotFoundError: No module named 'CreateMidiEventsForBass'

**Comment by amchaney** [comment]
@shenrichs What version of python are you running?  Are you invoking the command from the terminal?  This looks like a path problem, since it can't find the modules that are included in the project.  
I use Python installed via anaconda:
`Python 2.7.13 :: Anaconda 4.3.1 (x86_64)`
The old 2.7 version is necessary since the midi libraries used weren't compatible with Python 3.6
Once you have installed 2.7.13, and you are in the terminal, and have run the `pip` command you should be able to run the `wbDev.py` command from the `cd $WB_HOME/src` directory, since from that directory python can find its library friends.

I also run OSX Mojave 10.14.6, so you are good on that OS.
